apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-viewer-binding
subjects:
  - kind: ServiceAccount
    name: webserver-operator-controller-manager
    namespace: webserver-operator-system
roleRef:
  kind: ClusterRole
  name: system:kube-controller-manager
  apiGroup: rbac.authorization.k8s.io
