# permissions for end users to view webservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: webserver-operator
    app.kubernetes.io/managed-by: kustomize
  name: webserver-viewer-role
rules:
- apiGroups:
  - my.domain
  resources:
  - webservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - my.domain
  resources:
  - webservers/status
  verbs:
  - get
